require('dotenv').config();
const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const { randomUUID, randomBytes } = require('node:crypto');
const bcrypt = require('bcryptjs');
const request = require('supertest');
const prisma = require('../config/db');
const { createApp } = require('../app');
const { readConfig } = require('../config/env');
const { period, csvCell } = require('../services/adminService');
const prefix = `adminqa_${randomUUID().slice(0,8)}`;
const password = 'AdminQa@2026';
const config = readConfig({ ...process.env, JWT_SECRET: randomBytes(48).toString('hex'), OPENAI_API_KEY: '', GEMINI_API_KEY: '' });
const app = createApp(prisma, config), csrf = { 'X-CSRF-Protection': 'sg-restock-web', Origin: config.origin };
const users = [], cookies = [];
let profile, product, order, originalSetting, restoreVersion;
const business = { businessName: `${prefix} Đại lý`, warehouseAddress: '12 Đường kho kiểm thử', deliveryRadiusKm: 15, deliveryFee: 10000, region: prefix, taxCode: '0123456789', legalRepresentative: 'Người đại diện kiểm thử', verificationDocumentUrl: 'https://example.com/business-proof.pdf' };
const item = { name: `${prefix} Nước ngọt`, packaging: 'Thùng 24 lon', wholesalePrice: 200000, stockQty: 50, moq: 2 };
const today = new Date(Date.now() + 7*3600000).toISOString().slice(0,10);
const dates = { from: today, to: today };
const get = (path, who=0) => request(app).get('/api'+path).set('Cookie',cookies[who]);
const post = (path, body, who=0) => request(app).post('/api'+path).set(csrf).set('Cookie',cookies[who]).send(body);
const patch = (path, body, who=0) => request(app).patch('/api'+path).set(csrf).set('Cookie',cookies[who]).send(body);
const put = (path, body, who=0) => request(app).put('/api'+path).set(csrf).set('Cookie',cookies[who]).send(body);
async function signIn(index) {
  const result = await request(app).post('/api/auth/login').set(csrf).send({ username: users[index].username, password }).expect(200);
  cookies[index] = result.headers['set-cookie'][0].split(';')[0];
}
before(async () => {
  const passwordHash = await bcrypt.hash(password, 10);
  for (const role of ['ADMIN','SUPPLIER','STORE_OWNER','STORE_OWNER']) {
    users.push(await prisma.user.create({ data: { username: `${prefix}_${users.length}`, name: `${prefix} User`, passwordHash, role: { connect: { code: role } } } }));
    await signIn(users.length-1);
  }
  originalSetting = await prisma.platformSetting.findUniqueOrThrow({ where: { id: 1 } });
});
after(async () => {
  if (restoreVersion !== undefined) await prisma.platformSetting.updateMany({ where: { id: 1, version: restoreVersion }, data: { commissionRate: originalSetting.commissionRate, version: { increment: 1 } } });
  if (profile) await prisma.wholesaleOrder.deleteMany({ where: { supplierId: profile.id } });
  const ids = users.map(u=>u.id);
  await prisma.auditLog.deleteMany({ where: { actorId: { in: ids } } });
  await prisma.aiUsageEvent.deleteMany({ where: { userId: { in: ids } } });
  await prisma.recommendationRun.deleteMany({ where: { ownerId: { in: ids } } });
  await prisma.user.deleteMany({ where: { id: { in: ids } } });
  await prisma.$disconnect();
});
test('all admin endpoints require ADMIN, and writes require CSRF', async () => {
  for (const path of ['/users','/verifications','/settings','/settlements','/settlements/export','/analytics','/ai','/audit-logs']) {
    await request(app).get('/api/admin'+path).expect(401);
    for (const role of [1,2]) await get('/admin'+path,role).expect(403);
    await get('/admin'+path).expect(200);
  }
  await request(app).put('/api/admin/settings').set('Cookie',cookies[0]).send({commissionRate:1,version:0}).expect(403);
  await put('/admin/settings',{commissionRate:1,version:0},1).expect(403);
  await patch(`/admin/users/${users[1].id}/status`,{status:'BANNED'},2).expect(403);
  await post('/admin/settlements/1/receive',{reference:'test'},2).expect(403);
  const accounts = await get('/admin/users').query({q:prefix}).expect(200);
  assert.equal(accounts.body.total,3);
  assert.equal(JSON.stringify(accounts.body).includes('passwordHash'),false);
  await get('/admin/users').query({role:'ADMIN'}).expect(400);
  await get('/admin/analytics').query({from:'2026-02-30',to:'2026-03-01'}).expect(400);
  await get('/admin/analytics').query({from:'2020-01-01',to:'2026-01-01'}).expect(400);
  await get('/admin/users').query({page:'1 OR 1=1'}).expect(400);
});
test('supplier submits evidence, admin reviews once, and only approved listings are visible', async () => {
  profile = (await put('/supplier/profile',business,1).expect(200)).body.profile;
  product = (await post('/supplier/products',item,1).expect(201)).body.product;
  assert.equal(profile.verificationStatus,'DRAFT');
  assert.equal((await get('/catalog/products',2).query({q:prefix})).body.products.length,0);
  await post('/supplier/verification',{},1).expect(200);
  await post('/supplier/verification',{},1).expect(409);
  const list = await get('/admin/verifications').query({q:prefix,status:'PENDING'}).expect(200);
  profile = list.body.profiles[0];
  const review = {status:'APPROVED',version:profile.verificationVersion,note:'Đã kiểm tra hồ sơ thử nghiệm'};
  await patch(`/admin/verifications/${profile.id}`,review,1).expect(403);
  const outcomes = await Promise.all([patch(`/admin/verifications/${profile.id}`,review),patch(`/admin/verifications/${profile.id}`,review)]);
  assert.equal(outcomes.filter(r=>r.status===200).length,1);
  assert.ok(outcomes.every(r=>[200,409].includes(r.status)));
  const shown = await get('/catalog/products',2).query({q:prefix}).expect(200);
  assert.equal(shown.body.products[0].id,product.id);
  for(const field of ['taxCode','verificationDocumentUrl','email','passwordHash']) assert.equal(JSON.stringify(shown.body).includes(`"${field}"`),false);
});
test('checkout snapshots commission; delivery accrues once; collection is atomic and exported safely', async () => {
  const setting = (await get('/admin/settings')).body;
  await put('/admin/settings',{commissionRate:-1,version:setting.version}).expect(400);
  const first = await put('/admin/settings',{commissionRate:5.5,version:setting.version}).expect(200);
  restoreVersion = first.body.version;
  await put('/admin/settings',{commissionRate:80,version:setting.version}).expect(409);
  const body = {requestId:randomUUID(),recipientName:'Người nhận kiểm thử',recipientPhone:'0901234567',deliveryAddress:'12 Đường giao hàng kiểm thử',expectedDeliveryFee:10000,lines:[{productId:product.id,quantity:3,expectedUpdatedAt:product.updatedAt}],subtotal:1,commissionRate:0,buyerId:users[3].id};
  const results = await Promise.all([post('/orders',body,2),post('/orders',body,2)]);
  assert.ok(results.every(r=>[200,201].includes(r.status)),JSON.stringify(results.map(r=>r.body)));
  assert.equal(results[0].body.order.id,results[1].body.order.id);
  order = results[0].body.order;
  assert.equal(order.subtotal,600000);assert.equal(order.total,610000);assert.equal(order.commissionRate,5.5);
  assert.equal(order.buyer.id,users[2].id);
  await post('/orders',body,3).expect(409);
  assert.equal((await get('/orders',3)).body.orders.length,0);
  const next = await put('/admin/settings',{commissionRate:7.5,version:restoreVersion}).expect(200);
  restoreVersion = next.body.version;
  for(const status of ['APPROVED','PREPARING','SHIPPING','DELIVERED']) order = (await patch(`/supplier/orders/${order.id}/status`,{status},1).expect(200)).body.order;
  assert.equal(order.commissionAmount,33000);assert.ok(order.deliveredAt);
  await patch(`/supplier/orders/${order.id}/status`,{status:'DELIVERED'},1).expect(400);
  const debt = await get('/admin/settlements').query({...dates,supplierId:profile.id,status:'UNPAID'}).expect(200);
  assert.equal(debt.body.total,1);assert.equal(debt.body.totals.unpaid,33000);
  const report = await get('/admin/analytics').query({...dates,region:prefix}).expect(200);
  assert.equal(report.body.gmv,600000);assert.equal(report.body.completedOrders,1);assert.equal(report.body.commissionAccrued,33000);assert.equal(report.body.topProducts[0].quantity,3);
  const paid = await Promise.all([post(`/admin/settlements/${order.id}/receive`,{reference:'QA-receipt-001'}),post(`/admin/settlements/${order.id}/receive`,{reference:'QA-receipt-002'})]);
  assert.equal(paid.filter(r=>r.status===200).length,1);assert.equal(paid.filter(r=>r.status===409).length,1);
  const paidReport = await get('/admin/analytics').query({...dates,region:prefix}).expect(200);
  assert.equal(paidReport.body.commissionReceived,33000);assert.equal(paidReport.body.commissionUnpaid,0);
  const csv = await get('/admin/settlements/export').query({...dates,supplierId:profile.id}).expect(200);
  assert.match(csv.headers['content-type'],/text\/csv/);assert.match(csv.text,/33000/);assert.match(csv.text,/QA-receipt/);
  assert.equal(csvCell('=HYPERLINK("bad")'),'"\'=HYPERLINK(""bad"")"');
  const receiptLogs = await prisma.auditLog.count({where:{entityType:'ORDER',entityId:String(order.id),action:'COMMISSION_RECEIVED'}});
  assert.equal(receiptLogs,1);
});
test('suspension revokes sessions and hides suppliers; expiry and explicit unlock never revive old sessions', async () => {
  let user = (await get('/admin/users').query({q:users[1].username})).body.users[0];
  const suspendedUntil = new Date(Date.now()+3600000).toISOString();
  await patch(`/admin/users/${user.id}/status`,{status:'SUSPENDED',suspendedUntil,reason:'Tạm khóa kiểm thử',expectedUpdatedAt:user.updatedAt}).expect(200);
  await get('/supplier/dashboard',1).expect(401);
  await request(app).post('/api/auth/login').set(csrf).send({username:users[1].username,password}).expect(401);
  assert.equal((await get('/catalog/products',2).query({q:prefix})).body.products.length,0);
  user = (await get('/admin/users').query({q:users[1].username,status:'SUSPENDED'})).body.users[0];
  await patch(`/admin/users/${users[0].id}/status`,{status:'BANNED',reason:'Block admin test',expectedUpdatedAt:user.updatedAt}).expect(403);
  await patch(`/admin/users/${user.id}/status`,{status:'ACTIVE',reason:'Mở lại kiểm thử',expectedUpdatedAt:'2000-01-01'}).expect(409);
  await prisma.user.update({where:{id:user.id},data:{suspendedUntil:new Date(Date.now()-1000)}});
  await get('/supplier/dashboard',1).expect(401);
  await signIn(1);
  assert.equal((await get('/catalog/products',2).query({q:prefix})).body.products.length,1);
  user = (await get('/admin/users').query({q:users[1].username})).body.users[0];
  await patch(`/admin/users/${user.id}/status`,{status:'BANNED',reason:'Khóa vĩnh viễn thử nghiệm',expectedUpdatedAt:user.updatedAt}).expect(200);
  await get('/supplier/dashboard',1).expect(401);
  user = (await get('/admin/users').query({q:users[1].username})).body.users[0];
  await patch(`/admin/users/${user.id}/status`,{status:'ACTIVE',reason:'Kết thúc kiểm thử',expectedUpdatedAt:user.updatedAt}).expect(200);
  await signIn(1);
});
test('changing legal identity requires review again and stale KYC approval fails', async () => {
  const before = (await get('/admin/verifications').query({q:prefix})).body.profiles[0];
  const updated = await put('/supplier/profile',{...business,businessName:business.businessName+' mới',verificationStatus:'APPROVED'},1).expect(200);
  assert.equal(updated.body.profile.verificationStatus,'DRAFT');
  assert.equal((await get('/catalog/products',2).query({q:prefix})).body.products.length,0);
  await post('/supplier/verification',{},1).expect(200);
  await patch(`/admin/verifications/${profile.id}`,{status:'APPROVED',version:before.verificationVersion,note:'Stale review attempt'}).expect(409);
  const pending = (await get('/admin/verifications').query({q:prefix})).body.profiles[0];
  await patch(`/admin/verifications/${profile.id}`,{status:'REJECTED',version:pending.verificationVersion,note:'Cần bổ sung giấy tờ'}).expect(200);
  assert.equal((await get('/supplier/profile',1)).body.profile.verificationNote,'Cần bổ sung giấy tờ');
});
test('AI usage records real provider attempts and rule-based replies without prompts or credentials', async () => {
  await post('/advisor/chat',{message:'Hàng nào sắp hết?'},2).expect(200);
  const rule = await prisma.aiUsageEvent.findFirst({where:{userId:users[2].id},orderBy:{id:'desc'}});
  assert.equal(rule.provider,'RULES');assert.equal(rule.status,'SUCCESS');
  const geminiApp = createApp(prisma,{...config,aiProvider:'GEMINI',aiApiKey:'qa-secret-key',aiModel:'qa-model',aiFetcher:async(url,options)=>{
    assert.match(url,/generativelanguage.googleapis.com/);assert.equal(options.headers['x-goog-api-key'],'qa-secret-key');
    return {ok:true,json:async()=>({candidates:[{finishReason:'STOP',content:{parts:[{text:'Chưa đủ dữ liệu.'}]}}],usageMetadata:{promptTokenCount:12,candidatesTokenCount:5}})};
  }});
  await request(geminiApp).post('/api/advisor/chat').set(csrf).set('Cookie',cookies[2]).send({message:'Thông tin riêng kiểm thử'}).expect(200);
  const usage = await prisma.aiUsageEvent.findFirst({where:{userId:users[2].id,provider:'GEMINI'}});
  assert.equal(usage.inputTokens,12);assert.equal(usage.outputTokens,5);
  assert.equal(JSON.stringify(usage).includes('qa-secret-key'),false);assert.equal(JSON.stringify(usage).includes('Thông tin riêng'),false);
  const metrics = await get('/admin/ai').query(dates).expect(200);
  assert.ok(metrics.body.groups.some(g=>g.provider==='GEMINI'&&g.status==='SUCCESS'));
  assert.equal(metrics.body.weatherIntegrated,false);
});
test('acceptance metric counts a saved, matching server suggestion once and isolates owners', async () => {
  const start = new Date(Date.now()-8*86400000);
  const inventory = await prisma.inventoryItem.create({data:{ownerId:users[2].id,name:prefix+' kho',unit:'lon',quantity:0,createdAt:start}});
  await prisma.stockMovement.create({data:{itemId:inventory.id,type:'OPENING',quantityChange:30,quantityBefore:0,quantityAfter:30,productName:inventory.name,unit:'lon',note:'QA opening',createdAt:start}});
  await prisma.stockMovement.create({data:{itemId:inventory.id,type:'SALE',quantityChange:-30,quantityBefore:30,quantityAfter:0,productName:inventory.name,unit:'lon',note:'QA sale',createdAt:new Date(Date.now()-2*86400000)}});
  const forecast = (await get('/restock/forecast',2).expect(200)).body;
  assert.ok(forecast.recommendationRunId);
  const quantity = forecast.items.find(i=>i.itemId===inventory.id).suggestedQuantity;assert.ok(quantity>0);
  const plan = {requestId:randomUUID(),name:'QA plan',note:'',horizonDays:7,safetyDays:2,recommendationRunId:forecast.recommendationRunId,lines:[{itemId:inventory.id,quantity}]};
  await post('/restock/plans',plan,3).expect(404);
  await post('/restock/plans',plan,2).expect(201);
  await post('/restock/plans',plan,2).expect(200);
  const run = await prisma.recommendationRun.findUnique({where:{id:forecast.recommendationRunId}});
  assert.ok(run.acceptedAt);
  const metrics = await get('/admin/ai').query(dates).expect(200);
  assert.ok(metrics.body.acceptedRuns>=1);assert.ok(metrics.body.acceptanceRate<=100);
});
test('audit is read-only and does not include password hashes', async () => {
  const result = await get('/admin/audit-logs').query({...dates,entityId:String(order.id)}).expect(200);
  assert.ok(result.body.logs.some(l=>l.action==='ORDER_STATUS_CHANGED'));
  assert.ok(result.body.logs.some(l=>l.action==='COMMISSION_RECEIVED'));
  assert.equal(JSON.stringify(result.body).includes('passwordHash'),false);
  await request(app).delete('/api/admin/audit-logs/1').set(csrf).set('Cookie',cookies[0]).expect(404);
  assert.equal(period({from:'2026-09-22',to:'2026-09-22'}).start.toISOString(),'2026-09-21T17:00:00.000Z');
});
